version: '3.1'

services:
  db:
    container_name: "tfgdb"
    image: "postgres:latest"
    restart: "always"
    environment:
      POSTGRES_PASSWORD: "alefelice01"
    ports:
      - "5432:5432"
    networks:
      - "tfg-network"

  web_scrapper:
    container_name: "tfgscrapper"
    build: "./web_scrapper"
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
    restart: "always"
    ports:
      - "8000:8000"
    networks:
      - "tfg-network"
    expose: 
      - "8000"
  
  web_service:
    container_name: "tfgservice"
    build: "./web_api"
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8080"
    restart: "always"
    ports:
      - "8080:8080"
    networks:
      - "tfg-network"
    depends_on:
      - "db"
      - "web_scrapper"
    expose: 
      - "8080"
      - "4000"
  
networks:
  tfg-network:
      external: true
      driver: "bridge"
      name: "tfg-network"


    
