version: '3.1'

  
networks:
  tfg-network1:
      driver: "bridge"

services:
  db:
    container_name: "tfgdb"
    image: "postgres:latest"
    restart: "always"
    environment:
      POSTGRES_PASSWORD: "alefelice01"
    ports:
      - "5432:5432"
    networks:
      - "tfg-network1"

  web_scrapper:
    user: "root"
    container_name: "tfgscrapper"
    build: "./web_scrapper"
    command: bash -c "daphne -u https -p 8000 --keyfile /app/certs/privkey1.pem --certfile /app/certs/cert1.pem -b 0.0.0.0 web_scrapper.asgi:application"
    restart: "always"
    ports:
      - "8000:8000"
    networks:
      - "tfg-network1"
    expose: 
      - "8000"
  
  web_service:
    container_name: "tfgservice"
    build: "./web_api"
    command: bash -c "python3 manage.py migrate && gunicorn -b 0.0.0.0:8080 web_api.wsgi:application"
    restart: "always"
    ports:
      - "4000:4000"
      - "8080:8080"
    networks:
      - "tfg-network1"
    depends_on:
      - "db"
      - "web_scrapper"
    expose: 
      - "8080"
      - "4000"