# Generated by Django 3.2.20 on 2023-11-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
