# Generated by Django 3.2.20 on 2023-11-29 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_assignment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='grade',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.grade'),
        ),
    ]
