# Generated by Django 3.2.20 on 2023-11-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sesion_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='grade',
        ),
        migrations.AddField(
            model_name='quiz',
            name='grade',
            field=models.ManyToManyField(null=True, to='core.Grade'),
        ),
    ]
