# Generated by Django 3.2.20 on 2023-11-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20231130_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='grade',
            field=models.ManyToManyField(null=True, to='core.Grade'),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='grade',
        ),
        migrations.AddField(
            model_name='assignment',
            name='grade',
            field=models.ManyToManyField(null=True, to='core.Grade'),
        ),
    ]
