# Generated by Django 3.2.20 on 2023-11-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20231130_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='grade',
            field=models.ManyToManyField(to='core.Grade'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='grade',
            field=models.ManyToManyField(to='core.Grade'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='grade',
            field=models.ManyToManyField(to='core.Grade'),
        ),
    ]
