# Generated by Django 3.2.20 on 2023-12-26 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20231222_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
    ]
