# Generated by Django 3.2.20 on 2024-01-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_sesion_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='grade',
        ),
    ]
