# Generated by Django 3.2.20 on 2024-01-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_attendance_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='grade',
        ),
        migrations.AddField(
            model_name='sesion',
            name='grade',
            field=models.ManyToManyField(to='core.Grade'),
        ),
    ]
