# Generated by Django 3.2.20 on 2024-01-09 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
