# Generated by Django 3.2.20 on 2024-02-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_teacher_update_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.IntegerField(default=-1, unique=True),
        ),
    ]
