# Generated by Django 3.2.20 on 2024-03-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_course_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='name',
        ),
    ]
