# Generated by Django 3.2.20 on 2024-03-06 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_attendance_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('objective', models.ManyToManyField(to='core.Objective')),
            ],
        ),
    ]
