# Generated by Django 3.2.20 on 2024-03-06 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_globalscores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalscores',
            name='objective',
        ),
        migrations.AddField(
            model_name='globalscores',
            name='objective',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.objective'),
        ),
    ]
