# Generated by Django 3.2.20 on 2024-03-07 11:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20240306_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('objective', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.objective')),
                ('student', models.ManyToManyField(to='core.Student')),
            ],
        ),
    ]
