# Generated by Django 3.2.20 on 2024-03-18 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_studentscores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalscores',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentscores',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
