# Generated by Django 3.2.20 on 2024-03-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20240318_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='objective',
        ),
        migrations.AddField(
            model_name='assignment',
            name='objective',
            field=models.ManyToManyField(to='core.Objective'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='objective',
        ),
        migrations.AddField(
            model_name='quiz',
            name='objective',
            field=models.ManyToManyField(to='core.Objective'),
        ),
    ]
