# Generated by Django 3.2.20 on 2024-03-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20240319_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'group')},
        ),
    ]
